# src/memory/atomizer.py
"""
Memory Atomizer: Decompose L0 reasoning traces into L1 structured atoms.

Two modes:
- LLM mode (default): Uses OpenAI API for rich, context-aware extraction
- Rule mode (fallback): Keyword/heuristic extraction for deterministic tests

[CITATION: MEMORY-ATOMIZER]
[CITATION: TencentDB2026]
"""

import os
import time
import json
from typing import Dict, List, Optional, Any
from dataclasses import dataclass

from shared.utils.citations import cite
from memory.architecture import MemoryTrace
from memory.layered_models import MemoryAtom, AtomType


@cite(
    key="ATOMIZER",
    paper="Layered Memory Architecture: Trace Atomization",
    venue="ACN Architecture Document",
    section="L0→L1 Decomposition",
    rationale="Structured atom extraction enables hierarchical memory abstraction",
    confidence="HIGH",
)
class MemoryAtomizer:
    """
    Decompose reasoning traces (L0) into atomic facts (L1).

    Usage:
        atomizer = MemoryAtomizer(mode="llm")  # or "rule" for deterministic
        atoms = atomizer.atomize(trace, twin_signature)
    """

    def __init__(
        self,
        mode: str = "auto",
        model: str = "gpt-4o-mini",
        api_key: Optional[str] = None,
    ):
        self.mode = mode  # "llm", "rule", or "auto" (try llm, fallback to rule)
        self.model = model
        self._api_key = api_key or os.environ.get("OPENAI_API_KEY")
        self._client: Optional[Any] = None

    def _get_client(self) -> Any:
        if self._client is None:
            try:
                from openai import OpenAI
                self._client = OpenAI(api_key=self._api_key)
            except ImportError as exc:
                raise RuntimeError("openai package not installed") from exc
        return self._client

    def atomize(
        self,
        trace: MemoryTrace,
        twin_signature: Optional[Dict[str, Any]] = None,
    ) -> List[MemoryAtom]:
        """
        Decompose a MemoryTrace into MemoryAtoms.

        Args:
            trace: The L0 memory trace to atomize
            twin_signature: Optional cognitive signature for context-aware extraction

        Returns:
            List of MemoryAtom objects
        """
        if self.mode == "llm":
            return self._atomize_llm(trace, twin_signature)
        elif self.mode == "rule":
            return self._atomize_rule(trace, twin_signature)
        else:  # auto
            if self._api_key:
                try:
                    return self._atomize_llm(trace, twin_signature)
                except Exception:
                    pass
            return self._atomize_rule(trace, twin_signature)

    def _atomize_llm(
        self,
        trace: MemoryTrace,
        twin_signature: Optional[Dict[str, Any]],
    ) -> List[MemoryAtom]:
        """LLM-based atomization with structured JSON output."""
        content = self._extract_text(trace)
        if not content or len(content) < 10:
            return []

        system_prompt = (
            "You are a memory atomizer. Extract structured atomic facts from the given "
            "reasoning trace. Return a JSON object with key 'atoms', where each atom has: "
            "atom_type (one of: claim, insight, correction, outcome, meta_cognitive, hypothesis, recommendation), "
            "content (the fact, max 200 chars), confidence (0.0-1.0), tags (list of keywords). "
            "Extract only substantive facts, not filler or restatements."
        )

        twin_context = ""
        if twin_signature:
            twin_context = (
                f"\nThis reasoning was generated by twin '{twin_signature.get('name', 'unknown')}' "
                f"(cluster: {twin_signature.get('cluster', 'unknown')}). "
                f"Consider their epistemology ({twin_signature.get('epistemic_engine', {}).get('primary', 'unknown')}) "
                f"when judging what counts as insight vs claim."
            )

        user_prompt = f"Extract atoms from this reasoning trace:{twin_context}\n\n---\n{content[:4000]}\n---"

        client = self._get_client()
        response = client.chat.completions.create(
            model=self.model,
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            response_format={"type": "json_object"},
            max_tokens=1024,
            temperature=0.2,
        )

        raw = response.choices[0].message.content or "{}"
        parsed = json.loads(raw)
        atoms_data = parsed.get("atoms", [])

        atoms = []
        for item in atoms_data:
            try:
                atom = MemoryAtom.create(
                    atom_type=AtomType(item.get("atom_type", "claim")),
                    content=item.get("content", ""),
                    source_trace_id=trace.trace_id,
                    twin_id=trace.source or "unknown",
                    confidence=item.get("confidence", 0.7),
                    tags=item.get("tags", []),
                )
                atoms.append(atom)
            except (ValueError, KeyError):
                continue
        return atoms

    def _atomize_rule(
        self,
        trace: MemoryTrace,
        twin_signature: Optional[Dict[str, Any]],
    ) -> List[MemoryAtom]:
        """
        Rule-based atomization for deterministic, fast extraction.

        Uses keyword heuristics to classify sentences into atom types.
        No LLM required — suitable for testing and offline operation.
        """
        content = self._extract_text(trace)
        if not content:
            return []

        sentences = self._split_sentences(content)
        atoms = []
        twin_id = trace.source or "unknown"

        for sentence in sentences:
            sentence = sentence.strip()
            if len(sentence) < 10:
                continue

            atom_type, confidence, tags = self._classify_sentence(sentence, twin_signature)
            if atom_type:
                atom = MemoryAtom.create(
                    atom_type=atom_type,
                    content=sentence[:300],
                    source_trace_id=trace.trace_id,
                    twin_id=twin_id,
                    confidence=confidence,
                    tags=tags,
                )
                atoms.append(atom)

        return atoms

    @staticmethod
    def _extract_text(trace: MemoryTrace) -> str:
        """Extract searchable text from a MemoryTrace."""
        content = trace.content
        if isinstance(content, str):
            return content
        if isinstance(content, dict):
            # Collect all string values from the reasoning dict
            texts = []
            for key, value in content.items():
                if isinstance(value, str) and len(value) > 5:
                    texts.append(value)
                elif isinstance(value, list):
                    for item in value:
                        if isinstance(item, str) and len(item) > 5:
                            texts.append(item)
                        elif isinstance(item, dict) and "critique" in item:
                            c = item.get("critique", "")
                            if isinstance(c, str):
                                texts.append(c)
            return " ".join(texts)
        return str(content)

    @staticmethod
    def _split_sentences(text: str) -> List[str]:
        """Simple sentence splitter."""
        import re
        # Split on period, exclamation, question mark followed by space or end
        sentences = re.split(r'(?<=[.!?])\s+', text)
        return [s.strip() for s in sentences if s.strip()]

    @staticmethod
    def _classify_sentence(
        sentence: str,
        twin_signature: Optional[Dict[str, Any]],
    ) -> tuple:
        """
        Classify a sentence into an atom type using keyword heuristics.

        Returns: (AtomType or None, confidence, tags)
        """
        lower = sentence.lower()
        tags = []

        # Meta-cognitive: confidence, bias, realization about own thinking
        meta_keywords = [
            "confidence", "overconfident", "underconfident", "bias", "realized",
            "noticed", "became aware", "reflecting", "self-critique", "skeptical",
            "what makes me skeptical", "my recommendation", "i recommend",
        ]
        if any(kw in lower for kw in meta_keywords):
            if "recommend" in lower or "my recommendation" in lower:
                return AtomType.RECOMMENDATION, 0.75, ["meta", "recommendation"]
            return AtomType.META_COGNITIVE, 0.7, ["meta", "self_awareness"]

        # Correction: fix, adjust, revise, wrong, incorrect, mistake
        correction_keywords = [
            "correction", "fixed", "adjust", "revise", "wrong", "incorrect",
            "mistake", "error", "should have", "instead of", "revised",
            "update", "changed my mind", "counter-example",
        ]
        if any(kw in lower for kw in correction_keywords):
            return AtomType.CORRECTION, 0.75, ["correction", "learning"]

        # Outcome: result, passed, failed, achieved, outcome
        outcome_keywords = [
            "result", "passed", "failed", "achieved", "outcome", "benchmark",
            "accuracy", "score", "performance", "evaluated", "tested",
            "verification", "proved", "demonstrated",
        ]
        if any(kw in lower for kw in outcome_keywords):
            return AtomType.OUTCOME, 0.8, ["outcome", "evaluation"]

        # Insight: novel realization, connection, discovered
        insight_keywords = [
            "insight", "discovered", "realized", "key insight", "surprising",
            "novel", "unexpected", "connection", "analogy", "pattern",
            "breakthrough", "aha", "crucial", "fundamental",
        ]
        if any(kw in lower for kw in insight_keywords):
            return AtomType.INSIGHT, 0.8, ["insight", "discovery"]

        # Hypothesis: assume, hypothesize, speculate, maybe, might
        hypothesis_keywords = [
            "hypothesis", "assume", "speculate", "possibly", "might be",
            "could be", "tentative", "provisional", "unclear if",
            "uncertain whether", "appears that", "suggests that",
        ]
        if any(kw in lower for kw in hypothesis_keywords):
            return AtomType.HYPOTHESIS, 0.6, ["hypothesis", "tentative"]

        # Claim: factual assertion with stronger language
        claim_keywords = [
            "is", "are", "was", "were", "must", "should", "always", "never",
            "because", "therefore", "thus", "consequently", "proves",
            "demonstrates", "shows that", "indicates",
        ]
        if any(kw in lower for kw in claim_keywords):
            # Boost confidence for shorter, clearer sentences
            conf = 0.7 if len(sentence) < 150 else 0.6
            return AtomType.CLAIM, conf, ["claim", "assertion"]

        # Fallback: if sentence is substantive but doesn't match anything
        if len(sentence) > 30:
            return AtomType.CLAIM, 0.5, ["unclassified"]

        return None, 0.0, []
